# Summary

* [QUAL-O-TEU-DESTINO-DIVERSOS](README.md)
* [QUAL O TEU DESTINO?](qual_o_teu_destino.md)
* [O QUE SUCEDEU NUMA TRINCHEIRA](o_que_sucedeu_numa_trincheira.md)
* [OS LENHADORES](os_lenhadores.md)
* [DORMINDO NA CANOA](dormindo_na_canoa.md)
* [A FAVOR OU CONTRA](a_favor_ou_contra.md)
* [A VOLTA DO SOLDADO FERIDO](a_volta_do_soldado_ferido.md)
* [O FILHO PRÓDIGO](o_filho_prodigo.md)
* [A GRAÇA DE DEUS](a_graca_de_deus.md)
* [NÃO É PARA MIM!](nao_e_para_mim.md)
* [GANHO PELO AMOR](ganho_pelo_amor.md)
* [O AVARENTO DE MARSELHA](o_avarento_de_marselha.md)
* [A PÉROLA INIGUALÁVEL](a_perola_inigualavel.md)
* [DOIS MORRERAM POR MIM](dois_morreram_por_mim.md)
* [A MÃO CICATRIZADA](a_mao_cicatrizada.md)
* [SEU SALVADOR OU SEU JUIZ?](seu_salvador_ou_seu_juiz.md)
* [CULPADO, PORÉM PERDOADO](culpado,_porem_perdoado.md)
* [O PERDÃO RECUSADO](o_perdao_recusado.md)
* [COMO FOI NOS DIAS DE NOÉ](como_foi_nos_dias_de_noe.md)
* [ESTE MUNDO É COMO UM NAVIO PRESTES A AFUNDAR](este_mundo_e_como_um_navio_prestes_a_afundar.md)
* [CÉU OU INFERNO?](ceu_ou_inferno.md)
* [“PERIGO! ENTRADA PROIBIDA!”](perigo_entrada_proibida.md)
* [LIVRE DA COVA](livre_da_cova.md)
* [A PORTA ASSINALADA COM SANGUE](a_porta_assinalada_com_sangue.md)
* [FIQUE ONDE O FOGO JÁ QUEIMOU](fique_onde_o_fogo_ja_queimou.md)
* [SALVO!](salvo.md)
* [O CHÃO DA CASA](o_chao_da_casa.md)
* [EXEMPLO OU SUBSTITUTO?](exemplo_ou_substituto.md)
* [AVENTAIS DE FOLHAS OU TÚNICAS DE PELES?](aventais_de_folhas_ou_tunicas_de_peles.md)
* [O QUE SIGNIFICA “CRER”?](o_que_significa_crer.md)
* [CINCO COISAS QUE ANDAM JUNTAS](cinco_coisas_que_andam_juntas.md)
* [UM PREGADOR DA ANTIGA ESCOLA](um_pregador_da_antiga_escola.md)
* [UM ULTIMO AVISO ou “POR UM TRIZ”](um_ultimo_aviso_ou_por_um_triz.md)
* [BOA NOITE OU... ADEUS!](boa_noite_ou_adeus.md)
