[book]

type='livros'
subtype=''


bookdir='chapter-a-day-ap'

title='Chapter a Day - Apocalipse'

authors=['"Norman Berry"']

cat=['"Livros","Comentários"']

################################################################################
################################################################################
################################################################################

# AUTOR: DESCONHECIDOS

#Types
    #folhetos
	#subtype 
    	    #doutrinarios
            #evangelisticos

    #livretes
    #livros

#cat 
   #Evangelisticos
   #Doutrinarios
   #Livros
   #Livretes
   




multilingual=false
src='src'


[output.html]
additional-js=['custom.js']
additional-css=['book.css']


