[book]

title='Vida Através da Morte'

bookdir='vida-atraves-da-morte'

authors=['Charles Stanley']





multilingual=false
src='src'


[output.html]
additional-js=['custom.js']
additional-css=['book.css']


