sed -i 's/1 //g' juntos.txt
sed -i 's/2 //g' juntos.txt
sed -i 's/3 //g' juntos.txt
sed -i 's/4 //g' juntos.txt
sed -i 's/5 //g' juntos.txt
sed -i 's/6 //g' juntos.txt
sed -i 's/7 //g' juntos.txt
sed -i 's/8 //g' juntos.txt
sed -i 's/9 //g' juntos.txt
sed -i 's/0 //g' juntos.txt
