#!/bin/bash


# configurar link corretamente


sed -i 's/_1\:/_1\//g' *.html
sed -i 's/_2\:/_2\//g' *.html
sed -i 's/_3\:/_3\//g' *.html
sed -i 's/_4\:/_4\//g' *.html
sed -i 's/_5\:/_5\//g' *.html
sed -i 's/_6\:/_6\//g' *.html
sed -i 's/_7\:/_7\//g' *.html
sed -i 's/_8\:/_8\//g' *.html
sed -i 's/_9\:/_9\//g' *.html
sed -i 's/_10\:/_10\//g' *.html
sed -i 's/_11\:/_11\//g' *.html
sed -i 's/_12\:/_12\//g' *.html
sed -i 's/_13\:/_13\//g' *.html
sed -i 's/_14\:/_14\//g' *.html
sed -i 's/_15\:/_15\//g' *.html
sed -i 's/_16\:/_16\//g' *.html
sed -i 's/_17\:/_17\//g' *.html
sed -i 's/_18\:/_18\//g' *.html
sed -i 's/_19\:/_19\//g' *.html
sed -i 's/_20\:/_20\//g' *.html
sed -i 's/_21\:/_21\//g' *.html
sed -i 's/_22\:/_22\//g' *.html
sed -i 's/_23\:/_23\//g' *.html
sed -i 's/_24\:/_24\//g' *.html
sed -i 's/_25\:/_25\//g' *.html
sed -i 's/_26\:/_26\//g' *.html
sed -i 's/_27\:/_27\//g' *.html
sed -i 's/_28\:/_28\//g' *.html
sed -i 's/_29\:/_29\//g' *.html
sed -i 's/_30\:/_30\//g' *.html
sed -i 's/_31\:/_31\//g' *.html
sed -i 's/_32\:/_32\//g' *.html
sed -i 's/_33\:/_33\//g' *.html
sed -i 's/_34\:/_34\//g' *.html
sed -i 's/_35\:/_35\//g' *.html
sed -i 's/_36\:/_36\//g' *.html
sed -i 's/_37\:/_37\//g' *.html
sed -i 's/_38\:/_38\//g' *.html
sed -i 's/_39\:/_39\//g' *.html
sed -i 's/_40\:/_40\//g' *.html
sed -i 's/_41\:/_41\//g' *.html
sed -i 's/_42\:/_42\//g' *.html
sed -i 's/_43\:/_43\//g' *.html
sed -i 's/_44\:/_44\//g' *.html
sed -i 's/_45\:/_45\//g' *.html
sed -i 's/_46\:/_46\//g' *.html
sed -i 's/_47\:/_47\//g' *.html
sed -i 's/_48\:/_48\//g' *.html
sed -i 's/_49\:/_49\//g' *.html
sed -i 's/_50\:/_50\//g' *.html
sed -i 's/_51\:/_51\//g' *.html
sed -i 's/_52\:/_52\//g' *.html
sed -i 's/_53\:/_53\//g' *.html
sed -i 's/_54\:/_54\//g' *.html
sed -i 's/_55\:/_55\//g' *.html
sed -i 's/_56\:/_56\//g' *.html
sed -i 's/_57\:/_57\//g' *.html
sed -i 's/_58\:/_58\//g' *.html
sed -i 's/_59\:/_59\//g' *.html
sed -i 's/_60\:/_60\//g' *.html
sed -i 's/_61\:/_61\//g' *.html
sed -i 's/_62\:/_62\//g' *.html
sed -i 's/_63\:/_63\//g' *.html
sed -i 's/_64\:/_64\//g' *.html
sed -i 's/_65\:/_65\//g' *.html
sed -i 's/_66\:/_66\//g' *.html
sed -i 's/_67\:/_67\//g' *.html
sed -i 's/_68\:/_68\//g' *.html
sed -i 's/_69\:/_69\//g' *.html
sed -i 's/_70\:/_70\//g' *.html
sed -i 's/_71\:/_71\//g' *.html
sed -i 's/_72\:/_72\//g' *.html
sed -i 's/_73\:/_73\//g' *.html
sed -i 's/_74\:/_74\//g' *.html
sed -i 's/_75\:/_75\//g' *.html
sed -i 's/_76\:/_76\//g' *.html
sed -i 's/_77\:/_77\//g' *.html
sed -i 's/_78\:/_78\//g' *.html
sed -i 's/_79\:/_79\//g' *.html
sed -i 's/_80\:/_80\//g' *.html
sed -i 's/_81\:/_81\//g' *.html
sed -i 's/_82\:/_82\//g' *.html
sed -i 's/_83\:/_83\//g' *.html
sed -i 's/_84\:/_84\//g' *.html
sed -i 's/_85\:/_85\//g' *.html
sed -i 's/_86\:/_86\//g' *.html
sed -i 's/_87\:/_87\//g' *.html
sed -i 's/_88\:/_88\//g' *.html
sed -i 's/_89\:/_89\//g' *.html
sed -i 's/_90\:/_90\//g' *.html
sed -i 's/_91\:/_91\//g' *.html
sed -i 's/_92\:/_92\//g' *.html
sed -i 's/_93\:/_93\//g' *.html
sed -i 's/_94\:/_94\//g' *.html
sed -i 's/_95\:/_95\//g' *.html
sed -i 's/_96\:/_96\//g' *.html
sed -i 's/_97\:/_97\//g' *.html
sed -i 's/_98\:/_98\//g' *.html
sed -i 's/_99\:/_99\//g' *.html
sed -i 's/_100\:/_100\//g' *.html
sed -i 's/_101\:/_101\//g' *.html
sed -i 's/_102\:/_102\//g' *.html
sed -i 's/_103\:/_103\//g' *.html
sed -i 's/_104\:/_104\//g' *.html
sed -i 's/_105\:/_105\//g' *.html
sed -i 's/_106\:/_106\//g' *.html
sed -i 's/_107\:/_107\//g' *.html
sed -i 's/_108\:/_108\//g' *.html
sed -i 's/_109\:/_109\//g' *.html
sed -i 's/_110\:/_110\//g' *.html
sed -i 's/_111\:/_111\//g' *.html
sed -i 's/_112\:/_112\//g' *.html
sed -i 's/_113\:/_113\//g' *.html
sed -i 's/_114\:/_114\//g' *.html
sed -i 's/_115\:/_115\//g' *.html
sed -i 's/_116\:/_116\//g' *.html
sed -i 's/_117\:/_117\//g' *.html
sed -i 's/_118\:/_118\//g' *.html
sed -i 's/_119\:/_119\//g' *.html
sed -i 's/_120\:/_120\//g' *.html
sed -i 's/_121\:/_121\//g' *.html
sed -i 's/_122\:/_122\//g' *.html
sed -i 's/_123\:/_123\//g' *.html
sed -i 's/_124\:/_124\//g' *.html
sed -i 's/_125\:/_125\//g' *.html
sed -i 's/_126\:/_126\//g' *.html
sed -i 's/_127\:/_127\//g' *.html
sed -i 's/_128\:/_128\//g' *.html
sed -i 's/_129\:/_129\//g' *.html
sed -i 's/_130\:/_130\//g' *.html
sed -i 's/_131\:/_131\//g' *.html
sed -i 's/_132\:/_132\//g' *.html
sed -i 's/_133\:/_133\//g' *.html
sed -i 's/_134\:/_134\//g' *.html
sed -i 's/_135\:/_135\//g' *.html
sed -i 's/_136\:/_136\//g' *.html
sed -i 's/_137\:/_137\//g' *.html
sed -i 's/_138\:/_138\//g' *.html
sed -i 's/_139\:/_139\//g' *.html
sed -i 's/_140\:/_140\//g' *.html
sed -i 's/_141\:/_141\//g' *.html
sed -i 's/_142\:/_142\//g' *.html
sed -i 's/_143\:/_143\//g' *.html
sed -i 's/_144\:/_144\//g' *.html
sed -i 's/_145\:/_145\//g' *.html
sed -i 's/_146\:/_146\//g' *.html
sed -i 's/_147\:/_147\//g' *.html
sed -i 's/_148\:/_148\//g' *.html
sed -i 's/_149\:/_149\//g' *.html
sed -i 's/_150\:/_150\//g' *.html

# mudar ink para bilibaOn

sed -i 's:mysword.info\/b?r\=1Co_:bibliaonline.com.br\/acf\/1co\/:g' *.html
sed -i 's:mysword.info\/b?r\=1Ch_:bibliaonline.com.br\/acf\/1cr\/:g' *.html
sed -i 's:mysword.info\/b?r\=1Jo_:bibliaonline.com.br\/acf\/1jo\/:g' *.html
sed -i 's:mysword.info\/b?r\=1Pe_:bibliaonline.com.br\/acf\/1pe\/:g' *.html
sed -i 's:mysword.info\/b?r\=1Ki_:bibliaonline.com.br\/acf\/1rs\/:g' *.html
sed -i 's:mysword.info\/b?r\=1Sa_:bibliaonline.com.br\/acf\/1sm\/:g' *.html
sed -i 's:mysword.info\/b?r\=1Th_:bibliaonline.com.br\/acf\/1ts\/:g' *.html
sed -i 's:mysword.info\/b?r\=1Ti_:bibliaonline.com.br\/acf\/1tm\/:g' *.html
sed -i 's:mysword.info\/b?r\=2Cr_:bibliaonline.com.br\/acf\/2cr\/:g' *.html
sed -i 's:mysword.info\/b?r\=2Co_:bibliaonline.com.br\/acf\/2co\/:g' *.html
sed -i 's:mysword.info\/b?r\=2Jo_:bibliaonline.com.br\/acf\/2jo\/:g' *.html
sed -i 's:mysword.info\/b?r\=2Pe_:bibliaonline.com.br\/acf\/2pe\/:g' *.html
sed -i 's:mysword.info\/b?r\=2Ki_:bibliaonline.com.br\/acf\/2rs\/:g' *.html
sed -i 's:mysword.info\/b?r\=2Sa_:bibliaonline.com.br\/acf\/2sm\/:g' *.html
sed -i 's:mysword.info\/b?r\=2Th_:bibliaonline.com.br\/acf\/2ts\/:g' *.html
sed -i 's:mysword.info\/b?r\=2Ti_:bibliaonline.com.br\/acf\/2tm\/:g' *.html
sed -i 's:mysword.info\/b?r\=3Jo_:bibliaonline.com.br\/acf\/3jo\/:g' *.html
sed -i 's:mysword.info\/b?r\=Hag_:bibliaonline.com.br\/acf\/ag\/:g' *.html
sed -i 's:mysword.info\/b?r\=Amo_:bibliaonline.com.br\/acf\/am\/:g' *.html
sed -i 's:mysword.info\/b?r\=Rev_:bibliaonline.com.br\/acf\/ap\/:g' *.html
sed -i 's:mysword.info\/b?r\=Act_:bibliaonline.com.br\/acf\/atos\/:g' *.html
sed -i 's:mysword.info\/b?r\=col_:bibliaonline.com.br\/acf\/cl\/:g' *.html
sed -i 's:mysword.info\/b?r\=son_:bibliaonline.com.br\/acf\/ct\/:g' *.html
sed -i 's:mysword.info\/b?r\=Dan_:bibliaonline.com.br\/acf\/dn\/:g' *.html
sed -i 's:mysword.info\/b?r\=Deu_:bibliaonline.com.br\/acf\/dt\/:g' *.html
sed -i 's:mysword.info\/b?r\=Ecc_:bibliaonline.com.br\/acf\/ec\/:g' *.html
sed -i 's:mysword.info\/b?r\=Ezr_:bibliaonline.com.br\/acf\/ed\/:g' *.html
sed -i 's:mysword.info\/b?r\=Eph_:bibliaonline.com.br\/acf\/ef\/:g' *.html
sed -i 's:mysword.info\/b?r\=Est_:bibliaonline.com.br\/acf\/et\/:g' *.html
sed -i 's:mysword.info\/b?r\=Exo_:bibliaonline.com.br\/acf\/ex\/:g' *.html
sed -i 's:mysword.info\/b?r\=Eze_:bibliaonline.com.br\/acf\/ez\/:g' *.html
sed -i 's:mysword.info\/b?r\=Php_:bibliaonline.com.br\/acf\/fp\/:g' *.html
sed -i 's:mysword.info\/b?r\=Phm_:bibliaonline.com.br\/acf\/fm\/:g' *.html
sed -i 's:mysword.info\/b?r\=Gal_:bibliaonline.com.br\/acf\/gl\/:g' *.html
sed -i 's:mysword.info\/b?r\=Gen_:bibliaonline.com.br\/acf\/gn\/:g' *.html
sed -i 's:mysword.info\/b?r\=Heb_:bibliaonline.com.br\/acf\/hb\/:g' *.html
sed -i 's:mysword.info\/b?r\=Hab_:bibliaonline.com.br\/acf\/hc\/:g' *.html
sed -i 's:mysword.info\/b?r\=Isa_:bibliaonline.com.br\/acf\/is\/:g' *.html
sed -i 's:mysword.info\/b?r\=Jud_:bibliaonline.com.br\/acf\/jd\/:g' *.html
sed -i 's:mysword.info\/b?r\=Joe_:bibliaonline.com.br\/acf\/jl\/:g' *.html
sed -i 's:mysword.info\/b?r\=Jon_:bibliaonline.com.br\/acf\/jn\/:g' *.html
sed -i 's:mysword.info\/b?r\=Joh_:bibliaonline.com.br\/acf\/jo\/:g' *.html
sed -i 's:mysword.info\/b?r\=Job_:bibliaonline.com.br\/acf\/jó\/:g' *.html
sed -i 's:mysword.info\/b?r\=Jer_:bibliaonline.com.br\/acf\/jr\/:g' *.html
sed -i 's:mysword.info\/b?r\=Jos_:bibliaonline.com.br\/acf\/js\/:g' *.html
sed -i 's:mysword.info\/b?r\=Jdg_:bibliaonline.com.br\/acf\/jz\/:g' *.html
sed -i 's:mysword.info\/b?r\=Luk_:bibliaonline.com.br\/acf\/lc\/:g' *.html
sed -i 's:mysword.info\/b?r\=Lam_:bibliaonline.com.br\/acf\/lm\/:g' *.html
sed -i 's:mysword.info\/b?r\=Lev_:bibliaonline.com.br\/acf\/lv\/:g' *.html
sed -i 's:mysword.info\/b?r\=Mar_:bibliaonline.com.br\/acf\/mc\/:g' *.html
sed -i 's:mysword.info\/b?r\=Mal_:bibliaonline.com.br\/acf\/ml\/:g' *.html
sed -i 's:mysword.info\/b?r\=Mic_:bibliaonline.com.br\/acf\/mq\/:g' *.html
sed -i 's:mysword.info\/b?r\=Mat_:bibliaonline.com.br\/acf\/mt\/:g' *.html
sed -i 's:mysword.info\/b?r\=Nah_:bibliaonline.com.br\/acf\/na\/:g' *.html
sed -i 's:mysword.info\/b?r\=Neh_:bibliaonline.com.br\/acf\/ne\/:g' *.html
sed -i 's:mysword.info\/b?r\=Num_:bibliaonline.com.br\/acf\/nm\/:g' *.html
sed -i 's:mysword.info\/b?r\=Oba_:bibliaonline.com.br\/acf\/ob\/:g' *.html
sed -i 's:mysword.info\/b?r\=Hos_:bibliaonline.com.br\/acf\/os\/:g' *.html
sed -i 's:mysword.info\/b?r\=Pro_:bibliaonline.com.br\/acf\/pv\/:g' *.html
sed -i 's:mysword.info\/b?r\=Rom_:bibliaonline.com.br\/acf\/rm\/:g' *.html
sed -i 's:mysword.info\/b?r\=Rut_:bibliaonline.com.br\/acf\/rt\/:g' *.html
sed -i 's:mysword.info\/b?r\=Zep_:bibliaonline.com.br\/acf\/sf\/:g' *.html
sed -i 's:mysword.info\/b?r\=Psa_:bibliaonline.com.br\/acf\/sl\/:g' *.html
sed -i 's:mysword.info\/b?r\=Jas_:bibliaonline.com.br\/acf\/tg\/:g' *.html
sed -i 's:mysword.info\/b?r\=Tit_:bibliaonline.com.br\/acf\/tt\/:g' *.html
sed -i 's:mysword.info\/b?r\=Zec_:bibliaonline.com.br\/acf\/zc\/:g' *.html



# cat cabecalho.txt *.html > index.md


